---
# defaults file for proxmox_datacenter

# This default must be overridden for any work to be performed.
# This value may either be a resolvable hostname or an IP address or
# a list of resolvable hostnames or IP addresses.
proxmox_api_host: 'pve.example.com'

# User for Proxmox API access to all API hosts above.
proxmox_api_user: 'root'

# Additional SSH options.
proxmox_api_port: 22
proxmox_api_sudo: false

# All groups will have recursive permissions created
# for path `/` and the `Administrator` role.
datacenter_groups: "{{ datacenter_users_groups }}"
datacenter_users: ['devops@pve']
datacenter_users_groups: ['Admin']
# All API tokens will have recursive permissions created
# for path `/` and the `Administrator` role.
datacenter_tokens: ['devops@pve!ansible']

local_token_secrets_dir: "{{ lookup('env', 'HOME') }}/.pve_tokens"
local_token_secret_name_prefix: ""
local_token_secret_name_suffix: ""
