---
# tasks file for proxmox_snippet

# The default `proxmox_snippet_path` is a directory that `corosync` keeps
# in sync across all the Proxmox hosts in a cluster.
# On this file system, the way `corosync` handles permissions causes the
# template task to fail when it must create the file.
# This task does not have the same problem and makes it work.
# It would not be needed for a normal directory path not controlled by `corosync`.
- name: Touch the file to overcome error when tempate creates the file.
  ansible.builtin.file:
    access_time: preserve
    modification_time: preserve
    path: "{{ proxmox_snippet_path }}/{{ proxmox_snippet_name }}"
    state: touch

- name: Create snippet.
  ansible.builtin.template:
    src: snippet.j2
    dest: "{{ proxmox_snippet_path }}/{{ proxmox_snippet_name }}"
